### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by oklengel** [j8sr0230/Nodes#130]
I tried to install the workbench with the freecad addon manager. 
System A;
**Windows 10, Freecad 0.19**, after installing, restart and switch to node workbench:
Errorlog:
```
13:57:59  No module named 'qtpy'
13:57:59  Traceback (most recent call last):
  File "<string>", line 43, in Initialize
  File "D:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\olive\AppData\Roaming\FreeCAD\Mod\Nodes\core\nodes_window.py", line 4, in <module>
    from qtpy.QtGui import QIcon, QKeySequence
  File "D:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
```

**System B, Mac mini M1, Freecad 0.20**:
Node WB is not visible after installation and restart.

**Comment by Emilien-Etadam** [comment]
Hello, 

Nodes is for FreeCAD version 0.21 or higher.
